In [19]:
#{{{{{{{{{BASIC ARRAY CREATION}}}}}}}}}
#(1)Programme for 1D array with elements [1,2,3,4,5]
import numpy as np
arr=np.array([1,2,3,4,5])
print("The 1D array is :\n",arr)

The 1D array is :
 [1 2 3 4 5]


In [18]:
#(2)Programme for 2D array with the elements [[1, 2, 3], [4, 5, 6]].
arr2=np.array([[1,2,3],[4,5,6]])
print("The 2D array is :\n",arr2)

The 2D array is :
 [[1 2 3]
 [4 5 6]]


In [15]:
#(3)Programme for 3x3 array filled with zeros.
arr3=np.zeros([3,3])
print("Zeroes array :\n",arr3)

Zeroes array :
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [16]:
# (4)Progarmme for 2x2 array filled with ones.
arr4=np.ones([2,2])
print("Ones array :\n",arr4)

Ones array :
 [[1. 1.]
 [1. 1.]]


In [17]:
#{{{{{{{{{ARRAY OPERATIONS}}}}}}}}}
''' (1)Create two arrays: a = [1, 2, 3] and b = [4, 5, 6].
(2) Perform element-wise addition, subtraction, multiplication, and division on these arrays.'''
a=np.array([1,2,3])
b=np.array([4,5,6])
addition=a+b
print("Array a ",a)
print("Array b",b)
print("Addition :\n",np.add(a,b))
print("Subtraction :\n",np.subtract(a,b))
print("Multiplication :\n",np.multiply(a,b))
print("Division :\n",np.divide(a,b))

Array a  [1 2 3]
Array b [4 5 6]
Addition :
 [5 7 9]
Subtraction :
 [-3 -3 -3]
Multiplication :
 [ 4 10 18]
Division :
 [0.25 0.4  0.5 ]


In [12]:
# {{{{{{{{{MATRIX MULTIPLICATION}}}}}}}}}
'''(1)Create two matrices: matrix_a = [[1, 2], [3, 4]] and matrix_b = [[5, 6], [7, 8]].
(2) Perform matrix multiplication on these matrices.'''
matrix_a=[[1,2],[3,4]]
matrix_b=[[5,6],[7,8]]
print("The Matrix Multiplication is :")
matrixmultiplication=np.dot(matrix_a,matrix_b)
print(matrixmultiplication)

The Matrix Multiplication is :
[[19 22]
 [43 50]]


In [11]:
#{{{{{{{{{{BROADCASTING}}}}}}}}}}
'''(1)Create an array: array = [1, 2, 3].
(2)Multiply this array by a scalar value, e.g., 2, using broadcasting.'''
array=np.array([1,2,3])
print("Array :\n",array)
scalar=2
#broadcasting
broadcast_array=array*scalar
print("Broadcasted array :\n",broadcast_array)



Array :
 [1 2 3]
Broadcasted array :
 [2 4 6]


In [20]:
#{{{{{{{{{{STATISTICAL OPERATIONS}}}}}}}}}}
'''(1)Create an array: data = [1, 2, 3, 4, 5].
(2)Calculate the mean, standard deviation, and sum of this array.'''
data=np.array([1,2,3,4,5])
mean_data=np.mean(data)
std_data=np.std(data)
sum_data=np.sum(data)
print("Data :\n",data)
print("Mean :\n",mean_data)
print("Standard Deviation :\n",std_data)
print("Sum :\n",sum_data)

Data :
 [1 2 3 4 5]
Mean :
 3.0
Standard Deviation :
 1.4142135623730951
Sum :
 15


In [21]:
#{{{{{{{{{{RESHAPING ARRAYS}}}}}}}}}}
'''(1)Create a 1D array: array = [1, 2, 3, 4, 5, 6].
(2)Reshape this array to a 2x3 array.
(3) Reshape the same array to a 3x2 array.'''
array=np.array([1,2,3,4,5,6])
print("Array :/n",array)
reshape_array=array.reshape(2,3)
reshapeagain_array=reshape_array.reshape(3,2)
print("2*3 array :/n",reshape_array)
print("3*2 array :/n",reshapeagain_array)

Array :/n [1 2 3 4 5 6]
2*3 array :/n [[1 2 3]
 [4 5 6]]
3*2 array :/n [[1 2]
 [3 4]
 [5 6]]


In [22]:
#{{{{{{{{{{ELEMENT WISE OPERATIONS}}}}}}}}}}
'''(1)Create two arrays: array_a = [1, 2, 3] and array_b = [4, 5, 6].
(2) Perform element-wise addition and multiplication on these arrays.'''
array_a=np.array([1,2,3])
array_b=np.array([4,5,6])
print("Array a :\n",array_a)
print("Array b :\n",array_b)
multi_array=np.multiply(array_a,array_b)
print("Multiplication :\n",multi_array)
add_array=np.add(array_a,array_b)
print("Addition :\n",add_array)

Array a :
 [1 2 3]
Array b :
 [4 5 6]
Multiplication :
 [ 4 10 18]
Addition :
 [5 7 9]


In [ ]:
array_a=np.array([1,2,3])
array_b=np.array([4,5,6])
print("A = ",array_a)
print("B = ",array_b)
dot_array=np.dot(array_a,array_b)
print("Dot product :\n",dot_array)

In [ ]:
#{{{{{{{{{{SLICING AND INDEXING}}}}}}}}}}
'''(1) Create a 2D array: array_2d = [[1, 2, 3], [4, 5, 6], [7, 8, 9]].
(2) Access the element at row 1, column 1.
(3) Access row 1.
(4) Access column 1.'''
array_2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array :\n",array_2D)
print("Access Array :\n")
access=array_2D[1,1]

row =array_2D[0,:]
column =array_2D[:,2]
print(access)
print("Row :\n",row)
print("Column :\n",column)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
5
[1 2 3]
[3 6 9]


In [ ]:
#{{{{{{{{{CREATING RANDOM ARRAYS}}}}}}}}}
'''(1) Create a 3x3 array with random floats.
(2) Create a 3x3 array with random integers between 0 and 10.'''
arr3=np.random.rand(3,3)
print("Random values array :\n",arr3)

arr4=np.random.randint(0,10,(3,3))
print("Intergers between 0 to 10 :\n",arr4)


[[0.30357219 0.89708461 0.88262885]
 [0.36612427 0.10856766 0.58366763]
 [0.4133215  0.46085094 0.49645984]]
[[5 6 1]
 [1 4 9]
 [5 9 7]]


In [23]:
#{{{{{{{{{STACKING AND CONCATENATING ARRAYS}}}}}}}}}
'''(1)Create two arrays: array_a = [1, 2, 3] and array_b = [4, 5, 6].
(2)Perform vertical stacking on these arrays.
(3) Perform horizontal stacking on these arrays.
'''
array_a=np.array([1,2,3])
array_b=np.array([4,5,6])
print("Array a :\n",array_a)
print("Array b :\n",array_b)
v_stack=np.vstack((array_a,array_b))
h_stack=np.hstack((array_a,array_b))
print("V stack :\n",v_stack)
print("H stack :\n",h_stack)

Array a :
 [1 2 3]
Array b :
 [4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [ ]:
#{{{{{{{{{{BASIC ARRAY CREATION}}}}}}}}}}
#(1)Create an array with 10 equally spaced numbers between 0 and 1.
import numpy as np
print(np.linspace(0,1,10))


[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [ ]:
#(2)Create a 1D array of 20 random integers between 1 and 100.
array=np.random.randint(1,101,20)
print(array)

[18 70 87 68 39 66 10 51 88 20 31 59  6 99 55 20 73 75  8  1]


In [ ]:
#(3)Create a 2D array with the shape (4, 4) filled with the value 7.
array=np.array([[7,7,7,7],[7,7,7,7],[7,7,7,7],[7,7,7,7]])
print(array)


[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [ ]:
#(4)Create a 1D array of 10 elements with the same value, 3.14.
array=np.array([3.14])
piarr=np.array(str(array)*10)
print(piarr)

[3.14][3.14][3.14][3.14][3.14][3.14][3.14][3.14][3.14][3.14]


In [ ]:
#(5)Create a 2D array with the shape (3, 3) with values ranging from 1 to 9.
array=np.arange(1,10).reshape(3,3)
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#{{{{{{{{{{ARRAY OPERATIONS }}}}}}}}}}}
#(1)Create two arrays: a = [1, 3, 5, 7, 9] and b = [2, 4, 6, 8, 10]. Perform element-wise subtraction.
a=np.array([1,3,5,7,9])
b=np.array([2,4,6,8,10])
#sub=a-b
#print(sub)
#or
sub=np.subtract(a,b)
print(sub)

[-1 -1 -1 -1 -1]


In [ ]:
#(2)Multiply array a by 3: a = [2, 4, 6, 8].
import numpy as np
a=np.array([2,4,6,8])
multiply=a*3
print(multiply)

[ 6 12 18 24]


In [ ]:
#(3)Divide array a by 2: a = [10, 20, 30, 40].
import numpy as np
a=np.array([2,4,6,8])
divide= a/2
print(divide)



[1. 2. 3. 4.]


In [ ]:
#(4)Find the element-wise modulus of two arrays: a = [5, 10, 15], b = [2, 3, 4].
import numpy as np
a=np.array([5,10,15])
b=np.array([2,3,4])
modu=np.mod(a,b)
print(modu)


[1 1 3]


In [ ]:
#(5)Create two arrays: a = [1, 2, 3], b = [4, 5, 6]. Compute the dot product.
arr=np.array([1,2,3])
arr2=np.array([4,5,6])
pro=np.dot(arr,arr2)
print(pro)

32


In [ ]:
#{{{{{{{{{{MATRIX MULTIPLICATION}}}}}}}}}}
'''(1)Create two matrices: a = [[2, 3], [4, 5]] and b = [[1, 0], [0, 1]]. Perform matrix
multiplication.'''
a=np.array([[2,3],[4,5]])
b=np.array([[1,0],[0,1]])
matrix_mul=np.matmul(a,b)
print(matrix_mul)

[[2 3]
 [4 5]]


In [ ]:
#(2)Multiply a 3x3 matrix with a 3x1 vector.
a=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
vec_a=np.array([[1],[2],[3]])
mul=np.dot(a,vec_a)
print(mul)

[[[14]
  [32]
  [50]]]


In [ ]:
'''(3)Create a 4x4 identity matrix and multiply it by a 4x4 matrix filled with random
integers.'''
array=np.eye(4)
arra2=np.random.randint(1,10,(4,4))
multi=np.dot(array,arra2)
print(multi)


[[1. 6. 3. 8.]
 [3. 6. 5. 5.]
 [9. 3. 9. 7.]
 [6. 3. 3. 5.]]


In [ ]:
'''(4)Perform matrix multiplication on two 3x3 matrices: a = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
and b = [[9, 8, 7], [6, 5, 4], [3, 2, 1]].'''
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b =np.array= ([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
multi=np.matmul(a,b)
print(multi)

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [ ]:
#(5)Create a 2x3 matrix and a 3x2 matrix. Perform matrix multiplication.
ar=np.array([[2,3,4],[3,2,6]])
aar2=np.array([[2,3],[3,2],[5,6]])
mul=np.dot(ar,aar2)
print(mul)

[[33 36]
 [42 49]]


In [ ]:
#{{{{{{{{{{BROADCASTING}}}}}}}}}}
#(1)Create a 1D array: array = [10, 20, 30]. Subtract a scalar value, 5, using broadcasting.
arr = np.array([10, 20, 30])
scalar = 5
#broadcasting
sub = arr - scalar
print (sub)



[ 5 15 25]


In [ ]:

#(2)Create a 3x3 array and a 3x1 array. Add them using broadcasting.
a=np.arange(9).reshape(3,3)
print(a)
b=np.array([[1],[2],[3]])
print(b)
c=a+b
print(c)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1]
 [2]
 [3]]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]


In [ ]:
#(3)Divide a 4x4 array by a scalar value, 2, using broadcasting.
import numpy as np
arr=np.array([1,2,3,5,34,5,42,22,32,23,2,33,44,3,43,5])
aa=arr.reshape(4,4)
print(aa)
scalar=2
#broadcasting
div=aa/scalar
print(div)




[[ 1  2  3  5]
 [34  5 42 22]
 [32 23  2 33]
 [44  3 43  5]]
[[ 0.5  1.   1.5  2.5]
 [17.   2.5 21.  11. ]
 [16.  11.5  1.  16.5]
 [22.   1.5 21.5  2.5]]


In [ ]:
#(4)Create a 3x3 array and add 3 to each element using broadcasting.
arr=np.arange(9).reshape(3,3)
print(arr)
print(arr+3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [2]:
#(5)Multiply a 1D array of shape (5,) by a 2D array of shape (5, 5) using broadcasting.
import numpy as np
arr_1=np.array([1,2,3,4,5])
arr_2=np.array([[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
broadcasting=arr_1[:np.newaxis]*arr_2
print(broadcasting)

[[  6  14  24  36  50]
 [ 11  24  39  56  75]
 [ 16  34  54  76 100]
 [ 21  44  69  96 125]
 [ 26  54  84 116 150]]


In [ ]:
#{{{{{{{{{STATISTICAL OPERATIONS }}}}}}}}}
#(1)Calculate the median of the array: data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10].
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(np.median(arr))

5.5


In [ ]:
#(2)Calculate the mode of the array: data = [1, 2, 2, 3, 4, 4, 4, 5, 6].
from scipy import stats
arr=np.array([1,2,2,3,4,4,4,5,6,])
print(stats.mode(arr))

ModeResult(mode=4, count=3)


In [ ]:
#(3)Calculate the range of the array: data = [10, 20, 30, 40, 50].
arr=np.array([10,20,30,40,50])
range_find=np.ptp(arr)
print(range_find)

40


In [ ]:
#(4)Calculate the 25th percentile of the array: data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10].
arr=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
percentile_arr=np.percentile(arr,25)
print(percentile_arr)

3.25


In [ ]:
'''(5)Calculate the correlation coefficient between two arrays: a = [1, 2, 3, 4, 5] and b = [2,
4, 6, 8, 10].'''
a=[1,2,3,4,5]
b=[2,4,6,8,10]
correlation=np.corrcoef(a,b)
print(correlation)

[[1. 1.]
 [1. 1.]]


In [ ]:
#{{{{{{{{{{{RESHAPING ARRAYS}}}}}}}}}}}
#(1)Reshape a 1D array of 12 elements to a 3x4 array.
aar=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(aar.reshape(3,4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
#(2)Reshape a 2D array of shape (6, 2) to (3, 4).
aarr=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(aarr)
print(aarr.reshape(3,4))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
#(3)Create a 4x4 array and flatten it.
aa=np.array([[[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]]])
print(aa)
print(aa.flatten())


[[[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]
   [13 14 15 16]]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [ ]:
#(4)Reshape a 3D array of shape (2, 3, 4) to (4, 3, 2).
a=np.arange(24).reshape(2,3,4)
print(a)
b=a.reshape(4,3,2)
print(b)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


In [ ]:
#(5)Reshape a 1D array to a 2D array with 1 row and many columns.
aa1D=np.array([1,2,3,4,5,6,7,8,9,10])
aa2D=aa1D.reshape(1,-1)
print(aa1D)
print(aa2D)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5  6  7  8  9 10]]


In [ ]:
#{{{{{{{{{{{ELEMENT-WISE OPERATIONS }}}}}}}}}}}
#(1)Create two arrays: a = [1, 3, 5] and b = [2, 4, 6]. Perform element-wise division.
a = np.array([1,3,5])
b = np.array([2,4,6])
print(a/b)

[0.5        0.75       0.83333333]


In [ ]:
#(2)Create two arrays: a = [2, 4, 6] and b = [1, 3, 5]. Perform element-wise modulus.
a =np.array([2,4,6])
b =np.array([1,3,5])
print(a%b)

[0 1 1]


In [ ]:
#(3)Add 10 to each element in the array: a = [1, 2, 3, 4, 5].
aar=np.array([1,2,3,4,5])
ad=aar+10
print(aar)
print(ad)

[1 2 3 4 5]
[11 12 13 14 15]


In [ ]:
#(4)Subtract 5 from each element in the array: b = [10, 20, 30, 40, 50].
b = np.array([10,20,30,40,50])
sub=b-5
print(sub)


[ 5 15 25 35 45]


In [ ]:
#(5)Square each element in the array: c = [1, 2, 3, 4, 5].
c =np.array([1, 2, 3, 4, 5])
print(c**2)

[ 1  4  9 16 25]


In [ ]:
#{{{{{{{{{{SLICING AND INDEXING}}}}}}}}}}
'''(1)Create a 3D array: array_3d = [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]. Access
the element at [1, 1, 1].'''
array_3d=np.array([[[1, 2, 3],[4, 5, 6]],[[7,8,9],[10,11,12]]])
slic= array_3d[1,1,1]
print(slic)

11


In [4]:
'''(2)Slice the first layer of a 3D array: array_3d = [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11,
12]]].'''
array_3d =np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10, 11,12]]])
eleslice=array_3d[0:1,]
print(eleslice)

[[[1 2 3]
  [4 5 6]]]


In [5]:
'''(3)Access all elements in the last row of the array: array_2d = [[10, 20, 30], [40, 50, 60],
[70, 80, 90]].'''
array_2d =np.array([[10, 20, 30], [40, 50, 60],[70, 80, 90]])
elearray=array_2d[-1:,]
print(elearray)


[[70 80 90]]


In [7]:
'''(4)Access all elements in the first column of the array: array_2d = [[10, 20, 30], [40, 50,
60], [70, 80, 90]].'''
array_2d =np.array([[10, 20, 30], [40, 50,60], [70, 80, 90]])
elearr=array_2d[:,:-1]
print(elearr)

[[10 20]
 [40 50]
 [70 80]]


In [8]:
'''(5)Slice the last two rows and columns of the array: array_2d = [[10, 20, 30], [40, 50,
60], [70, 80, 90]].'''
array_2d = np.array([[10, 20, 30], [40, 50,60], [70, 80, 90]])
ele=array_2d[-2:,-2:]
print(ele)

[[50 60]
 [80 90]]


In [ ]:
#{{{{{{{{{{{CREATING RANDOM ARRAYS}}}}}}}}}}}
#(1)Generate a random array of 20 elements with values between 0 and 1.
aar=np.random.rand(20)
print(aar)

[0.81436467 0.43317458 0.1854284  0.15590971 0.21488365 0.57676791
 0.76901981 0.7336795  0.94451824 0.66553222 0.13186288 0.49591822
 0.66525686 0.40966559 0.71274736 0.4692521  0.55014491 0.80671165
 0.06785576 0.61938379]


In [ ]:
#(2)Create a 4x4 array with random integers between 10 and 20.
aar=np.random.randint(10,20,(4,4))
print(aar)

[[14 12 19 12]
 [19 15 15 15]
 [18 14 11 15]
 [12 18 14 15]]


In [ ]:
#(3)Create a 3x3 array with random floats between -1 and 1.
aa=np.random.randint(-1,1,(3,3))
print(aa)

[[-1  0 -1]
 [ 0 -1  0]
 [ 0 -1  0]]


In [ ]:
#(4)Generate an array of 15 random integers between 100 and 200.
rr=np.random.randint(100,200,15)
print(rr)

[122 179 136 181 175 127 182 107 135 176 111 181 126 187 183]


In [ ]:
#(5)Create a 5x5 array with random floats between 0 and 10.
a=np.random.randint(0,10,(5,5))
print(a)

[[3 0 7 0 3]
 [6 8 4 6 4]
 [4 0 6 9 2]
 [7 9 5 1 9]
 [8 3 3 1 7]]


In [ ]:
#{{{{{{{{{STACKING AND CONCATENATING ARRAYS}}}}}}}}}
#(1)Vertically stack two arrays: a = [[1, 2], [3, 4]] and b = [[5, 6], [7, 8]].
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
v_stack = np.vstack([arr1,arr2])
print(v_stack)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
#(2)Horizontally stack two arrays: a = [[1, 2], [3, 4]] and b = [[5, 6], [7, 8]].
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
h_stack=np.hstack([arr1,arr2])
print(h_stack)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
#(3)Concatenate two 1D arrays: a = [1, 2, 3] and b = [4, 5, 6].
a=np.array([1,2,3])
b=np.array([4,5,6])
con=np.concatenate([a,b])
print(con)

[1 2 3 4 5 6]


In [ ]:
'''(4)Concatenate two 3x3 arrays along rows: a = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] and b = [[10,
11, 12], [13, 14, 15], [16, 17, 18]].'''
a=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
b=np.array([[[10,11,12],[13,14,15],[16,17,18]]])
conc=np.concatenate((a,b),axis=0)
print(conc)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [ ]:
'''(5)Concatenate two 3x3 arrays along columns: a = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] and b =
[[10, 11, 12], [13, 14, 15], [16, 17, 18]].'''
a=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
b=np.array([[[10,11,12],[13,14,15],[16,17,18]]])
conci=conc=np.concatenate((a,b),axis=1)
print(conci)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]
  [13 14 15]
  [16 17 18]]]
